
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author admin
 */
public class loginpage extends javax.swing.JFrame {

    /**
     * Creates new form loginpage
     */
    public loginpage() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPasswordField1 = new javax.swing.JPasswordField();
        jPanel1 = new javax.swing.JPanel();
        adminpanal1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        username1 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        password1 = new javax.swing.JPasswordField();
        registerbutton1 = new javax.swing.JLabel();
        loginbutton1 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();

        jPasswordField1.setText("jPasswordField1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(null);

        adminpanal1.setBorder(javax.swing.BorderFactory.createTitledBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 2, true), "Admin Login", javax.swing.border.TitledBorder.CENTER, javax.swing.border.TitledBorder.TOP, new java.awt.Font("Comic Sans MS", 1, 24))); // NOI18N
        adminpanal1.setForeground(new java.awt.Color(255, 255, 255));
        adminpanal1.setOpaque(false);
        adminpanal1.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel4.setText("Password :");
        adminpanal1.add(jLabel4);
        jLabel4.setBounds(32, 126, 95, 26);

        username1.setBackground(new java.awt.Color(240, 240, 240));
        username1.setBorder(null);
        username1.setOpaque(false);
        username1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                username1ActionPerformed(evt);
            }
        });
        adminpanal1.add(username1);
        username1.setBounds(30, 90, 219, 23);

        jLabel12.setText("_______________________________");
        adminpanal1.add(jLabel12);
        jLabel12.setBounds(30, 90, 220, 40);

        jLabel5.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel5.setText("Create New Account");
        adminpanal1.add(jLabel5);
        jLabel5.setBounds(55, 247, 177, 26);

        jLabel6.setFont(new java.awt.Font("Comic Sans MS", 1, 18)); // NOI18N
        jLabel6.setText("Username :");
        adminpanal1.add(jLabel6);
        jLabel6.setBounds(32, 60, 100, 26);

        password1.setBackground(new java.awt.Color(240, 240, 240));
        password1.setBorder(null);
        password1.setOpaque(false);
        adminpanal1.add(password1);
        password1.setBounds(30, 160, 220, 23);

        registerbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schooldatabasemanagementsystem/button (2).png"))); // NOI18N
        registerbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        registerbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerbutton1MouseClicked(evt);
            }
        });
        adminpanal1.add(registerbutton1);
        registerbutton1.setBounds(65, 284, 150, 42);

        loginbutton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schooldatabasemanagementsystem/button.png"))); // NOI18N
        loginbutton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        loginbutton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                loginbutton1MouseClicked(evt);
            }
        });
        adminpanal1.add(loginbutton1);
        loginbutton1.setBounds(82, 194, 122, 42);

        jLabel14.setText("_______________________________");
        adminpanal1.add(jLabel14);
        jLabel14.setBounds(30, 160, 230, 30);

        jPanel1.add(adminpanal1);
        adminpanal1.setBounds(40, 30, 280, 350);

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/schooldatabasemanagementsystem/white-office-desk-table-with-laptop-smartphone-coffee-supplies_33795-133.jpg"))); // NOI18N
        jLabel7.setDebugGraphicsOptions(javax.swing.DebugGraphics.NONE_OPTION);
        jPanel1.add(jLabel7);
        jLabel7.setBounds(10, -220, 1020, 840);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 634, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 415, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void username1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_username1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_username1ActionPerformed

    private void loginbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_loginbutton1MouseClicked
         String Username =username1.getText();
        String Password =   String.valueOf(password1.getPassword());
     
       
             try {
                 Class.forName("com.mysql.jdbc.Driver");
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/student registration","root","");
            String up = "Select * from Adminregistration WHERE username=? and password=?" ;
            PreparedStatement psmt =con.prepareStatement(up);
           
            psmt.setString(1,Username);
            psmt.setString(2,Password);
            ResultSet rs = psmt.executeQuery();
            
            if(rs.next())
            {
                JOptionPane.showMessageDialog(this, "Login Successfully");
                adminHomePage hp=new adminHomePage();
                   dispose();
                hp.setVisible(true);
            }
            else
            {
                JOptionPane.showMessageDialog(this,"Username or Password is incorrect");
    
            }
              } catch (ClassNotFoundException ex) {
                 Logger.getLogger(loginpage.class.getName()).log(Level.SEVERE, null, ex);
             } catch (SQLException ex) {
            Logger.getLogger(loginpage.class.getName()).log(Level.SEVERE, null, ex);
        }
              
    }//GEN-LAST:event_loginbutton1MouseClicked

    private void registerbutton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerbutton1MouseClicked
   adminRegisteration ar = new adminRegisteration();
   dispose();
   ar.setVisible(true);
    }//GEN-LAST:event_registerbutton1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(loginpage.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new loginpage().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel adminpanal1;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JLabel loginbutton1;
    private javax.swing.JPasswordField password1;
    private javax.swing.JLabel registerbutton1;
    private javax.swing.JTextField username1;
    // End of variables declaration//GEN-END:variables

    void setVisible() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
